# Generated by Django 5.0.6 on 2024-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("zipcode", models.CharField(max_length=20)),
                ("available", models.BooleanField(default=False)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
